# Generated by Django 4.0.4 on 2025-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed'), (3, 'Pending')], default=1),
        ),
    ]
