// TODO: put them all to AWS Secrets
export const NEXT_PUBLIC_ACCESS_TOKEN_KEY = process.env.NEXT_PUBLIC_ACCESS_TOKEN_KEY || 'NEXT_PUBLIC_ACCESS_TOKEN_KEY'
export const NEXT_PUBLIC_REFRESH_TOKEN_KEY = process.env.NEXT_PUBLIC_REFRESH_TOKEN_KEY || 'NEXT_PUBLIC_REFRESH_TOKEN_KEY'